version: "3.7"

services:
    web:
        container_name: tree_studio_nginx_server
        build: ./DockerFiles/DjangoServer
        ports:
            - 8801:8000
        # command: sudo sh runServerBash.sh
        command: sudo python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./Volume/DjangoServer/TreeStudio:/code
        restart: always
        tty: true
        
    # testweb:
    #     container_name: django_test_server
    #     build: ./DockerFiles/DjangoServer
    #     ports:
    #         - 5566:5566
    #     command: sudo python manage.py runserver 0.0.0.0:5566
    #     volumes:
    #         - ./Volume/DjangoServer/mydjango:/code
    #         - ./Airflow_Volume/dags:/airflowDagsFolder
    #         - ./Airflow_Volume/deleteDags:/deletedDag
    #         - ./Airflow_Volume/tarFolder:/tarFolder
    #     networks:
    #         - my-network
    #     restart: always
    #     tty: true
