version: "3.7"

services:
    web:
        container_name: tree_studio_nginx_server
        build: ./DockerFiles/DjangoServer
        ports:
            - 8801:8000
        # command: sudo sh runServerBash.sh
        command: sudo python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./Volume/DjangoServer/TreeStudio:/code
        restart: always
        tty: true
        